#pragma once

/**
 * @brief Enum of all scene in the game
 *
 * IDs for each scene to organize story.
 * Used for scene lookup and choices.
 */
enum SceneID {
	START = 1,
	WIDEPATH = 2,
	FOGWOOD = 3,
	FIGHT_KRAAN = 4,
	UNDERGROWTH = 5,
	CLEARING = 6,
	FALLENTREE = 7,
	KAKARMI = 8,
	STREAM = 9,
	CONTINUE_FOREST = 10,
	CAMOUFLAGE = 11,
	APPROACH = 12,
	TRACK_PERIMETER = 13,
	INVESTIGATE_HUTS = 14,
	FIGHT_GIAK = 15,
	CALL_BIRD = 16,
	IGNORE_BIRD = 17,
	CONTINUE_TRACK = 18,
	LEAVE_TRACK = 19,
	CONFRONT_STRANGER = 20,
	KILLED_MAGE = 21,
	TAKE_MAGE_GEM = 22,
	RUN_FROM_GIAKS = 23,
	APPROACH_MERCHANTS = 24,
	WALK_OPPOSITE = 25,
	AVOID_CLEARING = 26,
	FELL_DEATH = 27,
	INVESTIGATE_SMOKE = 28,
	AVOID_SMOKE = 29,
	MARCHING = 30,
	BATTLE = 31,
	FIGHT_GOURGAZ = 32,
	FLEE_BATTLE = 33,
	CONTINUE_BATTLE = 34,
	DEFEND_PRINCE = 35,
	TOWN_END = 36,
	WALK_AWAY = 37,
	UNDEFINEDSCENE = 100
};